name: List S3

on:
  push:
    branches: [ "main" ]
permissions:
  id-token: write # Necessário para solicitar o token OIDC
  contents: read

jobs:
  read:
    name: "LS aws s3"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::604218333462:role/S4US-oidc
          aws-region: sa-east-1
      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 ls s3://devops-sec4us.oidc.s3-sec4us/
