name: List S3

on:
  push:
    branches: [ "main" ]
permissions:
  id-token: write # Necessário para solicitar o token OIDC
  contents: read

jobs:
  read:
    name: "LS aws s3"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::890664054962:role/ci--rust-lang--rustup
          aws-region: us-east-1
      
      - name: Get User Info
        run: |
          aws sts get-caller-identity
