name: AWS Test 2

on:
  push:
    branches: [ "main" ]
permissions:
  id-token: write # Necessário para solicitar o token OIDC
  contents: read

jobs:
  read:
    name: "LS aws s3"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Get User Info
        run: |
          aws sts get-caller-identity
          aws s3 ls s3://devops-sec4us.oidc.s3-sec4us/

